apiVersion: v1
kind: Service
metadata:
  name: nginx-service	#Наименование услуги
  labels:     	#Service Собственный лейбл
    app: nginx	# Установите ключ для приложения для Сервиса и значение для метки nginx
spec:	    # Это определение Сервиса, описывающее, как Сервис выбирает модули и как к ним можно получить доступ.
  selector:	    # Селектор тегов
    app: nginx	# Выберите модуль, содержащий тег app: nginx
  ports:
  - name: nginx-port	# Имя порта
    protocol: TCP	    # Тип протокола TCP / UDP
    port: 80	        # Другие группы контейнеров в кластере могут получить доступ к Сервису через порт 80
    nodePort: 8888   # Служба доступа через порт 32600 любого узла
    targetPort: 80	# Перенаправить запрос на порт 80 соответствующего пода
  type: NodePort	# Тип посылки, ClusterIP / NodePort / LoaderBalancer
