---
- hosts: "all"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: install and configure dependencies
       shell: |
               sudo apt-get update && sudo apt-get install -y apt-transport-https curl ca-certificates gnupg lsb-release

     - name: install gpg repo key docker
       shell: |
               curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

     - name: add docker repo
       shell: |
               echo \
                 "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                 $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

     - name: install docker
       shell: |
               sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io

     - name: add recomendeds docker kuberneties konfig
       shell: |
               cat <<EOF | sudo tee /etc/docker/daemon.json
               {
                "exec-opts": ["native.cgroupdriver=systemd"],
                "log-driver": "json-file",
                "log-opts": {
                "max-size": "100m"
                },
                "storage-driver": "overlay2"
                }
                EOF

     - name: Restart docker
       shell: |
               sudo systemctl enable docker
               sudo systemctl daemon-reload
               sudo systemctl restart docker

     - name: disable swap
       shell: |
               sudo swapoff -a
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

     - name: install gpg repo key kubernetes
       shell: |
               sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

     - name: add kuberneties repo
       shell: |
               echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

     - name: install kubernetes
       shell: |
               sudo apt-get update
               sudo apt-get install -y kubelet=1.20.6-00 kubeadm=1.20.6-00 kubectl=1.20.6-00
               sudo apt-mark hold kubelet kubeadm kubectl

         
# Setup a handler for checking Docker daemon using the below code
  handlers:
    - name: docker status
      service: name=docker state=started      

